---

- name: Download war file from Jenkins
  get_url:
    url: http://13.126.55.156:8080/jenkins/job/deployment_job/lastSuccessfulBuild/execution/node/3/ws/target/hello-1.0.war
    dest: "{{ tomcat_home }}/webapps/"
    username: ram
    password: "{{ jenkins_token }}"
    force_basic_auth: yes
    
- name: Start tomcat
  systemd:
    state: started
    name: tomcat.service
